name = "getmybrief"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "out"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://nqzhxukuvmdlpewqytpv.supabase.co"
